# Generated by Django 3.0.2 on 2020-04-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oshare', '0002_auto_20200408_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='USD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sign',
            field=models.CharField(default='$', max_length=8, null=True),
        ),
    ]
